#!/bin/bash
#
# Test the MongoDB image in OpenShift.
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.

set -exo nounset
shopt -s nullglob

source "$(dirname "${BASH_SOURCE}")/lib/init.sh"
trap oc_error ERR
trap oc_shutdown EXIT SIGINT

STARTTIME=$(date +%s)

oc_setup_client
test_mongo_pets

ret=$?; ENDTIME=$(date +%s); echo "$0 took $(($ENDTIME - $STARTTIME)) seconds"; exit "$ret"
