#!/bin/sh
# Fix permissions on the given directory to allow group read/write of 
# regular files and execute of directories.
find $@ -exec chown -R jboss:0 {} \;
find $@ -exec chmod -R ug+rwX {} \;
find $@ -type d -exec chmod ug+x {} +