#!/bin/bash

export IMAGE_NAME=${IMAGE_NAME:-centos/mongodb-34-tar-centos7-candidate}
export CIDFILE_SFX=${CIDFILE_SFX:-test_cidfiles}
export CIDFILE_DIR=${CIDFILE_DIR:-$(mktemp --suffix=${CIDFILE_SFX} -d)}

# User credentials
export MONGODB_USERDB=${MONGODB_USERDB:-"mydb1"}
export MONGODB_USERID=${MONGODB_USERID:-"user1"}
export MONGODB_USERPW=${MONGODB_USERPW:-"pass1"}

# Admin credentials
export MONGODB_SUDODB=${MONGODB_SUDODB:-"admin"}
export MONGODB_SUDOID=${MONGODB_SUDOID:-"admin"}
export MONGODB_SUDOPW=${MONGODB_SUDOPW:-"r00t1"}

# Config parameters
export MONGODB_QUIETS=${MONGODB_QUIETS:-"true"}
export MONGODB_RSNAME=${MONGODB_RSNAME:-"rs0"}
export MONGODB_KEYVAL=${MONGODB_KEYVAL:-"xxxxxxxxxxxx"}
export MONGODB_SVCVAL=${MONGODB_SVCVAL:-"mongodb"}

# Default ENV
export DEF_USERDB_ENV="-e MONGODB_DATABASE=${MONGODB_USERDB}"
export DEF_USERID_ENV="-e MONGODB_USER=${MONGODB_USERID}"
export DEF_USERPW_ENV="-e MONGODB_PASSWORD=${MONGODB_USERPW}"
export DEF_SUDOPW_ENV="-e MONGODB_ADMIN_PASSWORD=${MONGODB_SUDOPW}"
export DEF_QUIETS_ENV="-e MONGODB_QUIET=${MONGODB_QUIETS}"
export DEF_RSNAME_ENV="-e MONGODB_REPLICA_NAME=${MONGODB_RSNAME}"
export DEF_KEYVAL_ENV="-e MONGODB_KEYFILE_VALUE=${MONGODB_KEYVAL}"
export DEF_SVCVAL_ENV="-e MONGODB_SERVICE_NAME=${MONGODB_SVCVAL}"
export STANDALONE_ENV="${DEF_USERDB_ENV} ${DEF_USERID_ENV} ${DEF_USERPW_ENV} ${DEF_SUDOPW_ENV}"
export REPLICASET_ENV="${DEF_USERDB_ENV} ${DEF_USERID_ENV} ${DEF_USERPW_ENV} ${DEF_SUDOPW_ENV} ${DEF_RSNAME_ENV} ${DEF_KEYVAL_ENV} ${DEF_SVCVAL_ENV}"
